### ISSUE TITLE
named route

### ISSUE THREAD

**Issue by lplume** [dannykopping/spore#11]
here again, find the way to reproduce, in this example i will popping up the exception using twig, but im almost sure it cano be skipped by calling directly slim urlFor.

https://gist.github.com/4618927 here the code, i notice that the error comes by using two or more separate spore's addService, could it be something with the autorouting?

thanks for the patience

**Comment by dannykopping** [comment]
Hey @lplume

Sorry for taking so long to look into this.
It turns out you need to provide your named route as a string...

``` php
<p>{{ urlFor('test') }}</p>
```

In your gist, you had this:

```
urlFor: {{ urlFor(name) }}
```

Let me know if that helps you out
Cheers

**Comment by dannykopping** [comment]
This has been resolved

It turns out that I had a bit of silly code that would scan for new services and add them every time you call `addService`, instead of just running it once. It now scans for all services when the `$spore->run()` function is called.

Thanks for spotting this @lplume!
