### ISSUE TITLE
Proxy required for hyperlink traversal

### ISSUE THREAD

**Issue by nickshanks** [dannykopping/spore#23]
In the Diving-Deeper file, there is a hyperlink to http://https//github.com/codeguy/Slim/issues/439

To traverse this would require me to set up a proxy server called "https" to intercept HTTP requests on port 80, extract the second level of the request path and issue a sub-request to that host, using the remainder of the path as the sub-request's full path.
Or you could add a colon to the hyperlink. Whichever you think's easier, y'know. :-)

**Comment by dannykopping** [comment]
Haha, you win the prize for funniest issue!
Thanks for the tip...
Good luck hooking up the proxy :)

**Comment by dannykopping** [comment]
Fixed!
