### ISSUE TITLE
named route

### ISSUE THREAD

**Issue by lplume** [dannykopping/spore#9]
I got an errer using Slim urlFor method (which also affect slim/extra twig-urlfor), popping up:

Type: RuntimeException
Message: Named route already exists with name: <route name>
File: <project root>/vendor/dannykopping/slim/Slim/Router.php
Line: 201

although it is defined once. Any suggest?

**Comment by dannykopping** [comment]
Can you provide an example?

**Comment by lplume** [comment]
actually cannot reproduce.. something wrong with me
